# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Crysis
email: griffith.elias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Elias Griffith's blog, portfolio, and robotics website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: egriffithCH
github_username:  bb00

# Build settings
markdown: kramdown
